spring:
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: dubs
    password: test1234
    driver-class-name: oracle.jdbc.OracleDriver
    platform: oracle

logging.level:
  org.springframework.jdbc: DEBUG
  com.zaxxer.hikari: DEBUG